--Target records
INSERT INTO TARGET (ID_TARGET, DESCRIPTION, STATUS, CREATION_USER, CREATION_DATE) VALUES (1, 'NEW', 1, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET (ID_TARGET, DESCRIPTION, STATUS, CREATION_USER, CREATION_DATE) VALUES (2, 'FREQUENT', 1, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET (ID_TARGET, DESCRIPTION, STATUS, CREATION_USER, CREATION_DATE) VALUES (3, 'PREMIUM', 1, 'ADMIN', CURRENT_TIMESTAMP);

--Target config records
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (1, 'amount_total', 2, 1, NULL, 0, 99999, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (2, 'amount_total', 2, 1, NULL, 100001,	499999, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (3, 'amount_total', 2, 1, NULL, 500001,	NULL, 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (1, 'cant', 2, 1, NULL, 1, 1, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (2, 'cant', 2, 1, NULL, 2, 4, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (3, 'cant', 2, 1, NULL, 5, NULL, 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (1, 'rate', 1, 1, 0.15, NULL, NULL, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (2, 'rate', 1, 1, 0.1, NULL, NULL, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (3, 'rate', 1, 1, 0.05, NULL, NULL, 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (1, 'max', 1, 1, 500000, NULL, NULL, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (2, 'max', 1, 1, 1000000, NULL, NULL, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO TARGET_CONFIG (ID_TARGET, DESCRIPTION, TYPE_CONFIG, STATUS, FIXED_VALUE, MIN_VALUE, MAX_VALUE, CREATION_USER, CREATION_DATE) VALUES (3, 'max', 1, 1, 5000000, NULL, NULL, 'ADMIN', CURRENT_TIMESTAMP);